format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[🞈](#a6e3a1 bold)"
error_symbol = "[🞈](#f38ba8)"
vicmd_symbol = "[🞈](#f9e2af)"

[directory]
format = "[]($style)[(bg:#f808080 fg:#ffffff)$path](bg:#ffffff fg:#a84c8d)[ ]($style)"
style = "bg:#1a1b26 fg:#ffffff"

[git_branch]
format = "[]($style)[[ ](bg:#ffffff fg:#a84c8d bold)$branch](bg:#ffffff fg:#4c4f69)[ ]($style)"
style = "bg:#1a1b26 fg:#ffffff"
